name: Package and release

on:
  push:
    tags:
      - 'v*'

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the source code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          pip-install: build
      - name: Install FUSE development assets
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse3-dev
      - name: Build the package
        run: |
          python -m build
      - name: Release the package
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          generate_release_notes: true
